### PR TITLE
Fixes for Clang/LLVM warnings

### PR DESCRIPTION
**Pull request by goodlyrottenapple**
* Add `-Wno-unused-result` to `CMakeLists.txt` to suppress error due to https://bugs.llvm.org/show_bug.cgi?id=51228
* Rename `accounts` to `accounts_ptr` and `runvm` to `runvm_ptr` due to 
```
/home/sam/git/evm-semantics-nix-flake/node/vm/vm.h:55:10: error: declaration of 'runvm* accesslist::runvm' changes meaning of 'runvm' [-fpermissive]
   55 |   runvm* runvm;
      |          ^~~~~
/home/sam/git/evm-semantics-nix-flake/node/vm/vm.h:33:8: note: 'runvm' declared here as 'struct runvm'
   33 | struct runvm {
      |        ^~~~~
In file included from /home/sam/git/evm-semantics-nix-flake/node/vm/vm.cpp:7:
/home/sam/git/evm-semantics-nix-flake/node/vm/kevm/semantics.h:44:13: error: declaration of 'accounts* tx_result::accounts' changes meaning of 'accounts' [-fpermissive]
   44 |   accounts* accounts;
      |             ^~~~~~~~
In file included from /home/sam/git/evm-semantics-nix-flake/node/vm/vm.cpp:5:
/home/sam/git/evm-semantics-nix-flake/node/vm/vm.h:28:8: note: 'accounts' declared here as 'struct accounts'
   28 | struct accounts {
      |        ^~~~~~~~
```

### CODE REVIEW

**Comment by gtrepta** [comment]
What's the error and what version of llvm is this happening on? It seems kind of strange that we need to cast fread to void but fwrite is fine, this probably needs to be addressed in some other way.

**Comment by goodlyrottenapple** [comment]
> What's the error and what version of llvm is this happening on? It seems kind of strange that we need to cast fread to void but fwrite is fine, this probably needs to be addressed in some other way.

The error is the same as here https://bugs.llvm.org/show_bug.cgi?id=51228

Actually there are a few other changes that I've had to make to make the code compile in LLVM/Clang 11.1
I suspect there might be some config defaults that are different tho, because I get similar errors from other versions of clang too

**Review by gtrepta — APPROVED** [review]
LGTM. Feel free to let me know if you add any more changes.
